In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales', axis = 1)
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures( degree = 3, include_bias = 1)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
from sklearn.linear_model import Ridge

In [17]:
ridge_model = Ridge(alpha =10)

In [18]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [19]:
test_predictions = ridge_model.predict(X_test)

In [20]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [22]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [23]:
MAE,RMSE

(0.6296591346758599, 0.89163275417109)

In [24]:
from sklearn.linear_model import RidgeCV

In [34]:
ridge_cv_model = RidgeCV(scoring = 'neg_mean_absolute_error')

In [35]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [36]:
ridge_cv_model.alpha_

0.1

In [37]:
from sklearn.metrics import SCORERS

In [38]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [39]:
test_predictions = ridge_cv_model.predict(X_test)

In [40]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [41]:
MAE, RMSE

(0.466712411318231, 0.5945136671839375)

In [42]:
ridge_cv_model.coef_

array([ 0.        ,  5.90523815,  0.46316396,  0.68028713, -6.17743395,
        3.73671928, -1.40708382,  0.00624704,  0.11128917, -0.2617823 ,
        2.17135744, -0.51480159,  0.70587211,  0.60311504, -0.53271216,
        0.5716495 , -0.34685826,  0.36744388, -0.03938079, -0.12192939])

In [44]:
from sklearn.linear_model import LassoCV

In [47]:
lasso_cv_model = LassoCV(eps = 0.1)

In [48]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(eps=0.1)

In [49]:
lasso_cv_model.alpha_

0.4924531806474871

In [50]:
test_predictions = lasso_cv_model.predict(X_test)

In [51]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [52]:
MAE, RMSE

(0.6811456342837983, 1.0349127365478727)

In [53]:
lasso_cv_model.coef_

array([0.        , 0.97675148, 0.        , 0.        , 0.        ,
       3.8148913 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [54]:
# Elastic Net

In [55]:
from sklearn.linear_model import ElasticNetCV

In [56]:
elastic_cv_model = ElasticNetCV()

In [57]:
elastic_cv_model.fit(X_train, y_train)

ElasticNetCV()

In [58]:
elastic_cv_model.alpha_

0.009849063612949745

In [59]:
test_predictions = elastic_cv_model.predict(X_test)

In [60]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [61]:
MAE, RMSE

(0.6073934663174836, 0.7380261405790612)

In [62]:
elastic_cv_model.coef_

array([ 0.        ,  3.63348902,  0.53032652,  0.09973788, -1.23311224,
        2.8509185 , -0.02592592, -0.        ,  0.11839468,  0.        ,
       -0.58423654, -0.        , -0.31651951,  0.6350333 , -0.        ,
        0.        , -0.12020437,  0.02856388,  0.04175635,  0.08892607])